version: '3.3'

services:

  lgd-db:
    env_file: .env
    build:
      context: ./lgd-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data
    sysctls:
      - kernel.shmmax=4294967296
    volumes:
      - lgd-db-vol:/var/lib/postgresql/data
    restart: always
    networks:
      - lgd-net

  lgd-nominatim-sync:
    env_file: .env
    build:
      context: ./lgd-nominatim-sync
    depends_on:
      - lgd-db
    volumes:
      - lgd-nominatim-sync-vol:/lgd/nominatim/src/settings
    restart: on-failure
    networks:
      - lgd-net

  lgd-osmosis-sync:
    env_file: .env
    build:
      context: ./lgd-osmosis-sync
    depends_on:
      - lgd-db
    volumes:
      - lgd-osmosis-sync-vol:/lgd/osmosis/sync
    restart: on-failure
    networks:
      - lgd-net

  lgd-sparqlify-web:
    env_file: .env
    build:
      context: ./lgd-sparqlify-web
    ports:
      - ${SPARQLIFY_PORT}:7531
    depends_on:
      - lgd-db
    volumes:
      - lgd-sparqlify-web-vol:/lgd/sparqlify/conf
    restart: always
    networks:
      - lgd-net

volumes:
  lgd-db-vol:
  lgd-osmosis-sync-vol:
  lgd-nominatim-sync-vol:
  lgd-sparqlify-web-vol:

networks:
  lgd-net:

